
[GLOBAL]
pants_version="2.13.0"
pythonpath = ["%(buildroot)s/pants_plugins"]

backend_packages = [
                 "pants.backend.plugin_development",
                 "pants.backend.python",
                 "pants.backend.python.lint.docformatter",
                 "pants.backend.python.lint.black",
                 "pants.backend.python.lint.isort" ,
                 "pants.backend.docker",
                 "sendwave.pants_node",
                 ]
[source]
root_patterns = ["/pants_plugins", "/test_webpack"]

[node]
use_nvm = true

[python]
interpreter_constraints = [">=3.9"]

[anonymous-telemetry]
enabled = true
repo_id = "BB6CBFC17A66FAB02E3FA88C13113D25"

[docker]
build_verbose = true
