
[GLOBAL]
pants_version="2.9.0"
pythonpath = ["%(buildroot)s/pants_plugins"]
plugins = [
   "sendwave-pants-docker@https://github.com/waveremit/pants-docker/releases/download/v1.0/sendwave-pants-docker-1.0.tar.gz"
]

backend_packages = [
                 "pants.backend.plugin_development",
                 "pants.backend.python",
                 "pants.backend.python.lint.docformatter",
                 "pants.backend.python.lint.black",
                 "pants.backend.python.lint.isort" ,
                 "sendwave.pants_node",
                 "sendwave.pants_docker"
                 ]
[source]
root_patterns = ["/pants_plugins", "/test_webpack"]

[node]
use_nvm = true

[python]
interpreter_constraints = [">=3.9"]

[anonymous-telemetry]
enabled = true
repo_id = "BB6CBFC17A66FAB02E3FA88C13113D25"
